spring.application.name=gateway
server.port=8082

spring.mongodb.uri=mongodb://localhost:27017/px-gateway-db

px-ledger.url=http://192.168.0.57:8081

jwt.refreshExpiration=604800000

# Disable the infinite loop listener during tests
px-gateway.listener.enabled=true